name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: DamianReeves/write-file-action@master
        with:
          path: $HOME/.bashrc
          contents: |
            echo "Hello World!"
          write-mode: append
      - uses: actions/upload-artifact@v1
        with:
          name: profile
          path: ${{ env.home}}/.bashrc
